//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopFashion_VA_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Slider
    {
        public int ID { get; set; }
        public string Hinh { get; set; }
    }
}
