//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopFashion_VA_Store.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_SanPham
    {
        public int IDSanPham { get; set; }
        public string TenSanPham { get; set; }
        [DisplayFormat(DataFormatString = "{0:0,0 VNĐ}")]
        public Nullable<int> Gia { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> LuotThich { get; set; }
        public string HinhChinh { get; set; }
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuongTrongKho { get; set; }
        public Nullable<int> IDLoaiSP { get; set; }
    }
}
